# Temario y referencias {-}

**Todas las notas y material del curso estarán en este** [repositorio](https://github.com/felipegonzalez/metodos-analiticos-mcd-2023).

- Parte 1: Inferencia causal
  - Introducción a inferencia causal
  - Modelos probabilísticos gráficos
  - Estimación de efectos causales
  - Experimentos y controles
  - Contrafactuales de Rubin
  - Otros métodos de inferencia causal 

- Parte 2: Análisis de series de tiempo y pronósticos
  - Descomposición de series de tiempo
  - Ingeniería de entradas para datos de series de tiempo
  - Métodos clásicos para pronósticos
  - Modelo de espacio de estados
  - Inferencia causal para series de tiempo
  
### Evaluación {-}

- Tareas semanales (20%)
- Examen parcial (40% teórico)
- Un examen final (40% práctico)

### Material {-}

Cada semestre las notas cambian, en algunas partes considerablemente. Las
de este semestre están en [este repositorio](https://github.com/felipegonzalez/metodos-analiticos-mcd-2023),
incluyendo ejemplos, ejercicios y tareas.

### Referencias principales {-}

- Parte 1
  - [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/)
  - [Causal Inference in Statistics: a primer](https://www.wiley.com/en-us/Causal+Inference+in+Statistics:+A+Primer-p-9781119186847)
  - [Counterfactuals and Causal Inference: Methods and Principles for Social Research](https://www.cambridge.org/core/books/counterfactuals-and-causal-inference/5CC81E6DF63C5E5A8B88F79D45E1D1B7)
  
- Parte 2:
  - [Forecasting: Principles and Practice](https://otexts.com/fpp3/)
  - [Time Series Analysis by State Space Methods](https://academic.oup.com/book/16563)
  
### Otras referencias {-}

- [Pattern Recognition and Machine Learning](http://www.springer.com/us/book/9780387310732), @Bishop
- [The Book of Why](https://dl.acm.org/doi/10.5555/3238230)
- [Data Analysis Using Regression and Multilevel/Hierarchical Models](https://www.cambridge.org/highereducation/books/data-analysis-using-regression-and-multilevel-hierarchical-models/32A29531C7FD730C3A68951A17C9D983#overview)
- [An Introduction to State Space Time Series Analysis](https://books.google.com.mx/books/about/An_Introduction_to_State_Space_Time_Seri.html?id=OCmljPYfgkUC&redir_esc=y)
### Software: R y Rstudio {-}

Para hacer las tareas y exámenes pueden usar cualquier lenguaje o flujo de trabajo
que les convenga (R o Python, por ejemplo) - el único requisito esté basado en código y no
point-and-click.


