on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:

env:
  RENV_PATHS_ROOT: ~/renv

permissions:
  contents: write

name: Render and deploy Book

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update
        run: sudo apt-get update

      - name: Install curl
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        # uncomment and fill to pin a version
        # with:
        #   version: 0.9.105

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: '4.2.3'

      - uses: r-lib/actions/setup-renv@v2
      - name: Install cmdstan
        run: |
          cmdstanr::check_cmdstan_toolchain(fix = TRUE)
          cmdstanr::install_cmdstan(cores = 2)
        shell: Rscript {0}
        
      - name: Render book to all format
        # Add any command line argument needed
        run: |
          quarto render notas/ --to html
      - name: Deploy 🚀
        # only deploy when push to main
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: notas/_book
